name: Android CI

on:
  workflow_dispatch:
    inputs:
      version:
        description: "version number for this release."
        required: true

jobs:
  build:
    name: Build release apk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2

      - name: set up JDK 11
        uses: actions/setup-java@v3.3.0
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.4

      - name: Build with gradle
        uses: gradle/gradle-build-action@v2.1.5
        with:
          arguments: assembleRelease
      
      - name: Add apk to release entry
        uses: softprops/action-gh-release@v0.1.14
        with:
          draft: true
          name: ${{ github.event.input.version }} 
          tag_name: "v${{ github.event.inputs.version }}"
          target_commitish: ${{ env.TARGET_COMMITISH }}
          files: ${GITHUB_REPOSITORY}/app/build/outputs/apk/release/app-release.apk
